-- Run this whole file in the Supabase SQL editor.
-- It is safe to run again if you already ran the earlier version.

create table if not exists public.business_financials (
  id integer primary key default 1 check (id = 1),
  printer_spend numeric(12, 2) not null default 934.00
    check (printer_spend >= 0),
  filament_accessories_spend numeric(12, 2) not null default 628.36
    check (filament_accessories_spend >= 0),
  total_revenue numeric(12, 2) not null default 363.26
    check (total_revenue >= 0),
  updated_at timestamptz not null default now()
);

insert into public.business_financials (
  id,
  printer_spend,
  filament_accessories_spend,
  total_revenue
)
values (1, 934.00, 628.36, 363.26)
on conflict (id) do nothing;

alter table public.business_financials enable row level security;

drop policy if exists "Authenticated users can read business financials"
  on public.business_financials;
create policy "Authenticated users can read business financials"
  on public.business_financials
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert business financials"
  on public.business_financials;
create policy "Authenticated users can insert business financials"
  on public.business_financials
  for insert
  to authenticated
  with check (id = 1);

drop policy if exists "Authenticated users can update business financials"
  on public.business_financials;
create policy "Authenticated users can update business financials"
  on public.business_financials
  for update
  to authenticated
  using (id = 1)
  with check (id = 1);

create table if not exists public.business_expenses (
  id bigint generated by default as identity primary key,
  expense_date date not null default current_date,
  category text not null default 'Filament & accessories'
    check (category in ('Filament', 'Accessories', 'Filament & accessories')),
  description text not null check (char_length(trim(description)) > 0),
  amount numeric(12, 2) not null check (amount > 0),
  source_key text unique,
  created_at timestamptz not null default now()
);

-- Seeds the eight purchase batches already discussed. Batch 7 uses only
-- your S$206.09 share after your sister's S$103.50 contribution.
insert into public.business_expenses (
  expense_date,
  category,
  description,
  amount,
  source_key
)
values
  (current_date, 'Filament & accessories', 'Purchase batch 1', 60.20, 'initial-batch-1'),
  (current_date, 'Filament & accessories', 'Purchase batch 2', 59.34, 'initial-batch-2'),
  (current_date, 'Filament & accessories', 'Purchase batch 3', 34.18, 'initial-batch-3'),
  (current_date, 'Filament & accessories', 'Purchase batch 4', 36.71, 'initial-batch-4'),
  (current_date, 'Filament & accessories', 'Purchase batch 5', 38.20, 'initial-batch-5'),
  (current_date, 'Filament & accessories', 'Purchase batch 6', 38.19, 'initial-batch-6'),
  (current_date, 'Filament & accessories', 'Purchase batch 7 (your share)', 206.09, 'initial-batch-7'),
  (current_date, 'Filament & accessories', 'Purchase batch 8', 155.45, 'initial-batch-8')
on conflict (source_key) do nothing;

alter table public.business_expenses enable row level security;

drop policy if exists "Authenticated users can read business expenses"
  on public.business_expenses;
create policy "Authenticated users can read business expenses"
  on public.business_expenses
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can add business expenses"
  on public.business_expenses;
create policy "Authenticated users can add business expenses"
  on public.business_expenses
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update business expenses"
  on public.business_expenses;
create policy "Authenticated users can update business expenses"
  on public.business_expenses
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete business expenses"
  on public.business_expenses;
create policy "Authenticated users can delete business expenses"
  on public.business_expenses
  for delete
  to authenticated
  using (true);
