-- Little Keeps recurring business subscriptions.
-- Run this file once in the Supabase SQL editor.

create table if not exists public.business_subscriptions (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) > 0),
  monthly_amount numeric(12, 2) not null check (monthly_amount > 0),
  billing_day integer not null default 1 check (billing_day between 1 and 31),
  started_on date not null default current_date,
  status text not null default 'active'
    check (status in ('active', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.business_subscriptions enable row level security;

drop policy if exists "Authenticated users can read business subscriptions"
  on public.business_subscriptions;
create policy "Authenticated users can read business subscriptions"
  on public.business_subscriptions
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can add business subscriptions"
  on public.business_subscriptions;
create policy "Authenticated users can add business subscriptions"
  on public.business_subscriptions
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update business subscriptions"
  on public.business_subscriptions;
create policy "Authenticated users can update business subscriptions"
  on public.business_subscriptions
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete business subscriptions"
  on public.business_subscriptions;
create policy "Authenticated users can delete business subscriptions"
  on public.business_subscriptions
  for delete
  to authenticated
  using (true);
