-- Little Keeps: licensed Custom Pencil Clicker catalogue entry.
-- Safe to run more than once. Existing Admin edits are preserved.

insert into public.product_catalog (
  product_key,
  name,
  eyebrow,
  description,
  status,
  price_visible,
  usual_base_price,
  launch_base_price,
  launch_price_enabled,
  included_characters,
  extra_character_price,
  included_base_colours,
  included_cap_colours,
  included_letter_colours,
  extra_base_colour_price,
  extra_cap_colour_price,
  extra_letter_colour_price,
  minimum_characters,
  maximum_characters,
  base_print_minutes_fixed,
  base_print_minutes_per_character,
  keycap_print_minutes_per_character,
  assembly_minutes_per_item,
  image_path,
  production_notes,
  sort_order
)
values (
  'custom-pencil-clicker',
  'Custom Pencil Clicker Keychain',
  'A pencil made completely yours',
  'Build a pencil with one satisfying clicky block per letter, number or symbol, then personalise every colour.',
  'coming_soon',
  false,
  9.90,
  7.90,
  true,
  10,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  1,
  10,
  90,
  0,
  0,
  10,
  null,
  'Prepare one licensed Clickify 3D Pencil Body and matching Flat/Raised top per character. Confirm block, top, character, eraser, ferrule, wood, tip and end-cap colours before slicing.',
  25
)
on conflict (product_key) do nothing;
