-- Run this whole file once in the Supabase SQL editor.
-- It creates the persistent Printing → Picked → Inventory workflow.

create table if not exists public.production_jobs (
  id bigint generated by default as identity primary key,
  item_name text not null check (char_length(trim(item_name)) > 0),
  category text not null check (category in ('Base', 'Keycap')),
  quantity integer not null check (quantity > 0),
  stage text not null default 'printing'
    check (stage in ('printing', 'picked')),
  started_at timestamptz not null default now(),
  picked_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists production_jobs_stage_idx
  on public.production_jobs (stage, started_at);

alter table public.production_jobs enable row level security;

drop policy if exists "Authenticated users can read production jobs"
  on public.production_jobs;
create policy "Authenticated users can read production jobs"
  on public.production_jobs
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can add production jobs"
  on public.production_jobs;
create policy "Authenticated users can add production jobs"
  on public.production_jobs
  for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update production jobs"
  on public.production_jobs;
create policy "Authenticated users can update production jobs"
  on public.production_jobs
  for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete production jobs"
  on public.production_jobs;
create policy "Authenticated users can delete production jobs"
  on public.production_jobs
  for delete
  to authenticated
  using (true);

create or replace function public.complete_production_job(
  p_job_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_job public.production_jobs%rowtype;
begin
  select *
  into v_job
  from public.production_jobs
  where id = p_job_id
  for update;

  if not found then
    raise exception 'Production job not found';
  end if;

  if v_job.stage <> 'picked' then
    raise exception 'Production job must be picked before adding inventory';
  end if;

  update public.inventory_items
  set
    qty = qty + v_job.quantity,
    category = v_job.category,
    updated_at = now()
  where item_name = v_job.item_name;

  if not found then
    insert into public.inventory_items (
      item_name,
      qty,
      category,
      updated_at
    )
    values (
      v_job.item_name,
      v_job.quantity,
      v_job.category,
      now()
    );
  end if;

  delete from public.production_jobs
  where id = p_job_id;
end;
$$;

revoke all on function public.complete_production_job(bigint) from public;
grant execute on function public.complete_production_job(bigint)
  to authenticated;

create or replace function public.complete_production_jobs(
  p_job_ids bigint[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_requested_count integer;
  v_found_count integer;
  v_item record;
begin
  select count(*)
  into v_requested_count
  from (
    select distinct unnest(p_job_ids) as id
  ) selected_ids;

  if v_requested_count = 0 then
    raise exception 'Select at least one production job';
  end if;

  perform 1
  from public.production_jobs
  where id = any(p_job_ids)
  order by id
  for update;

  select count(*)
  into v_found_count
  from public.production_jobs
  where
    id = any(p_job_ids) and
    stage = 'picked';

  if v_found_count <> v_requested_count then
    raise exception
      'Every selected production job must exist and be picked';
  end if;

  for v_item in
    select
      item_name,
      category,
      sum(quantity)::integer as quantity
    from public.production_jobs
    where id = any(p_job_ids)
    group by item_name, category
  loop
    update public.inventory_items
    set
      qty = qty + v_item.quantity,
      category = v_item.category,
      updated_at = now()
    where item_name = v_item.item_name;

    if not found then
      insert into public.inventory_items (
        item_name,
        qty,
        category,
        updated_at
      )
      values (
        v_item.item_name,
        v_item.quantity,
        v_item.category,
        now()
      );
    end if;
  end loop;

  delete from public.production_jobs
  where id = any(p_job_ids);
end;
$$;

revoke all
  on function public.complete_production_jobs(bigint[])
  from public;

grant execute
  on function public.complete_production_jobs(bigint[])
  to authenticated;
